# Copyright 2026 Saluca LLC
# Licensed under the Apache License, Version 2.0
"""
Velamen — LLM Steganographic Channel (Frozen Distribution Engine)
=================================================================
Encodes/decodes messages using arithmetic coding over pre-frozen
token probability distributions. Cross-machine deterministic.

Requires:
  - A .hchan file generated by velamen.channel.freeze()
  - A shared key (passphrase or 32-byte hex)

Usage:
    velamen encode --msg "hello world" --channel alpha.hchan --key mysecret
    velamen decode --cover "The capital..." --channel alpha.hchan --key mysecret
"""

import hashlib
import math
import os
import struct

try:
    from cryptography.hazmat.primitives.ciphers.aead import ChaCha20Poly1305
    _HAS_CRYPTOGRAPHY = True
except ImportError:
    _HAS_CRYPTOGRAPHY = False

# Constants
NONCE_LEN = 12
TAG_LEN = 16
LENGTH_LEN = 4


def _derive_key(passphrase: str | bytes) -> bytes:
    """Derive a 32-byte key from a passphrase using PBKDF2-HMAC-SHA256."""
    if isinstance(passphrase, str):
        passphrase = passphrase.encode("utf-8")
    salt = b"velamen-channel-v1"
    return hashlib.pbkdf2_hmac("sha256", passphrase, salt, iterations=100_000)


def _encrypt(plaintext: bytes, key: bytes) -> bytes:
    """Encrypt with ChaCha20-Poly1305. Returns nonce + ciphertext + tag."""
    if not _HAS_CRYPTOGRAPHY:
        raise RuntimeError(
            "pip install cryptography  (or use raw=True to skip encryption)"
        )
    nonce = os.urandom(NONCE_LEN)
    ct = ChaCha20Poly1305(key).encrypt(nonce, plaintext, None)
    return nonce + ct


def _decrypt(data: bytes, key: bytes) -> bytes:
    """Decrypt ChaCha20-Poly1305 blob."""
    if not _HAS_CRYPTOGRAPHY:
        raise RuntimeError("pip install cryptography")
    nonce, ct = data[:NONCE_LEN], data[NONCE_LEN:]
    return ChaCha20Poly1305(key).decrypt(nonce, ct, None)


# Bit utilities

def _bytes_to_bits(data: bytes) -> list[int]:
    bits = []
    for byte in data:
        for i in range(7, -1, -1):
            bits.append((byte >> i) & 1)
    return bits


def _bits_to_bytes(bits: list[int]) -> bytes:
    while len(bits) % 8:
        bits.append(0)
    result = bytearray()
    for i in range(0, len(bits), 8):
        byte = 0
        for j in range(8):
            byte = (byte << 1) | bits[i + j]
        result.append(byte)
    return bytes(result)


# Integer arithmetic coding
#
# Uses the standard half/quarter renormalization AC scheme with integer
# registers (no floating point). This guarantees encode/decode are exact
# inverses regardless of token probability distribution shape.
#
# stego.encode() = AC DECODE (bits -> tokens): treat message as compressed
# stego.decode() = AC ENCODE (tokens -> bits): treat cover text as the source
#
# PREC-bit registers; frequencies scaled to CSCL (2^20) to avoid overflow
# in 64-bit intermediate products (rng * CSCL fits in 64 bits when rng < 2^32).

_PREC = 32
_TOP = 1 << _PREC
_HALF = _TOP >> 1
_QRTR = _TOP >> 2
_CSCL = 1 << 20


def _cum(dist: list[dict]) -> list[tuple[str, int, int]]:
    """
    Convert a probability distribution to integer cumulative frequencies.
    Returns [(token, cum_lo, cum_hi)] with all values in [0, _CSCL].
    Each token has frequency >= 1 so no interval is zero-width.
    """
    freqs = [max(1, round(e["prob"] * _CSCL)) for e in dist]
    diff = _CSCL - sum(freqs)
    if diff:
        idx = freqs.index(max(freqs))
        freqs[idx] = max(1, freqs[idx] + diff)
    result, c = [], 0
    for e, f in zip(dist, freqs):
        result.append((e["token"], c, c + f))
        c += f
    return result


def _bits_to_tokens(bits: list[int], dists: list[list[dict]]) -> list[str]:
    """
    AC decoder: treat `bits` as the compressed stream and expand to tokens.
    After all message bits are consumed, the zero-padded tail naturally
    selects high-probability (greedy) tokens.
    """
    padded = bits + [0] * (_PREC * 2 + 64)

    value, ptr = 0, 0
    for _ in range(_PREC):
        value = (value << 1) | padded[ptr]; ptr += 1

    low, high = 0, _TOP - 1
    tokens = []

    for dist in dists:
        c = _cum(dist)
        rng = high - low + 1
        cum_pos = ((value - low + 1) * _CSCL - 1) // rng

        tok, sym_lo, sym_hi = c[-1][0], c[-1][1], c[-1][2]
        for t, lo, hi in c:
            if lo <= cum_pos < hi:
                tok, sym_lo, sym_hi = t, lo, hi
                break
        tokens.append(tok)

        high = low + (rng * sym_hi) // _CSCL - 1
        low = low + (rng * sym_lo) // _CSCL

        while True:
            if high < _HALF:
                pass
            elif low >= _HALF:
                low -= _HALF; high -= _HALF; value -= _HALF
            elif low >= _QRTR and high < _HALF + _QRTR:
                low -= _QRTR; high -= _QRTR; value -= _QRTR
            else:
                break
            low = low << 1
            high = (high << 1) | 1
            value = (value << 1) | padded[ptr]; ptr += 1

    return tokens


def _tokens_to_bits(tokens: list[str], dists: list[list[dict]]) -> list[int]:
    """
    AC encoder: compress token sequence to bits.
    The output bit stream is exactly what _bits_to_tokens would need as input
    to reproduce the same token sequence.
    """
    low, high, pending = 0, _TOP - 1, 0
    bits_out: list[int] = []

    def emit(b: int) -> None:
        nonlocal pending
        bits_out.append(b)
        for _ in range(pending):
            bits_out.append(1 - b)
        pending = 0

    for tok, dist in zip(tokens, dists):
        c = _cum(dist)
        sym_lo = sym_hi = None
        for t, lo, hi in c:
            if t == tok:
                sym_lo, sym_hi = lo, hi
                break
        if sym_lo is None:
            continue

        rng = high - low + 1
        high = low + (rng * sym_hi) // _CSCL - 1
        low = low + (rng * sym_lo) // _CSCL

        while True:
            if high < _HALF:
                emit(0); low = low << 1; high = (high << 1) | 1
            elif low >= _HALF:
                emit(1); low = (low - _HALF) << 1; high = (high - _HALF) << 1 | 1
            elif low >= _QRTR and high < _HALF + _QRTR:
                pending += 1; low = (low - _QRTR) << 1; high = (high - _QRTR) << 1 | 1
            else:
                break

    pending += 1
    emit(0 if low < _QRTR else 1)

    return bits_out


def encode(message: str, channel: dict, key: str, raw: bool = False) -> str:
    """
    Encode a message into cover text using frozen distributions.

    Args:
        message:  Plaintext to hide
        channel:  Loaded .hchan dict from velamen.channel.freeze()
        key:      Shared passphrase
        raw:      If True, skip encryption (testing only)

    Returns:
        cover_text: Natural-looking text with message encoded inside
    """
    dists = channel["distributions"]

    msg_bytes = message.encode("utf-8")
    if raw:
        payload = struct.pack(">I", len(msg_bytes)) + msg_bytes
    else:
        derived = _derive_key(key)
        ciphertext = _encrypt(msg_bytes, derived)
        payload = struct.pack(">I", len(ciphertext)) + ciphertext

    bits = _bytes_to_bits(payload)
    n_bits = len(bits)

    capacity_bits = sum(
        -sum(e["prob"] * math.log2(e["prob"]) for e in d if e["prob"] > 0)
        for d in dists
    )
    if n_bits > capacity_bits:
        raise ValueError(
            f"Message too large: {n_bits} bits needed, "
            f"channel holds ~{capacity_bits:.0f} bits "
            f"({capacity_bits / 8:.1f} bytes)"
        )

    return "".join(_bits_to_tokens(bits, dists))


def decode(cover_text: str, channel: dict, key: str, raw: bool = False) -> str:
    """
    Decode a hidden message from cover text using frozen distributions.

    Args:
        cover_text: Text produced by encode()
        channel:    Same .hchan used during encoding
        key:        Same passphrase used during encoding
        raw:        If True, skip decryption (testing only)

    Returns:
        Recovered plaintext message
    """
    dists = channel["distributions"]

    tokens: list[str] = []
    remaining = cover_text
    for dist in dists:
        if not remaining:
            tokens.append(dist[0]["token"])
            continue
        matched = None
        for e in sorted(dist, key=lambda x: -len(x["token"])):
            if remaining.startswith(e["token"]):
                matched = e["token"]
                break
        if matched is None:
            matched = remaining[0]
        tokens.append(matched)
        remaining = remaining[len(matched):]

    recovered_bits: list[int] = []
    payload_len: int = 0
    needed_bits: int = LENGTH_LEN * 8
    found = False

    for n in range(1, len(tokens) + 1):
        recovered_bits = _tokens_to_bits(tokens[:n], dists[:n])
        if len(recovered_bits) < LENGTH_LEN * 8:
            continue
        if needed_bits == LENGTH_LEN * 8:
            length_bytes_tmp = _bits_to_bytes(list(recovered_bits[:LENGTH_LEN * 8]))
            payload_len = struct.unpack(">I", length_bytes_tmp)[0]
            if payload_len > 64 * 1024 * 1024:
                raise ValueError(f"Implausible payload length: {payload_len}")
            needed_bits = (LENGTH_LEN + payload_len) * 8
        if len(recovered_bits) >= needed_bits:
            found = True
            break

    if not found:
        raise ValueError("Not enough bits recovered to read full payload.")

    payload_bits = list(recovered_bits[LENGTH_LEN * 8: LENGTH_LEN * 8 + payload_len * 8])
    payload = _bits_to_bytes(payload_bits)

    if raw:
        return payload.decode("utf-8", errors="replace")
    else:
        derived = _derive_key(key)
        plaintext = _decrypt(payload, derived)
        return plaintext.decode("utf-8")
